// src/provenance.js — AI transparency labels (IBM AI FactSheet style).
//
// Three content buckets get distinct provenance treatments:
//   1. ai-from-source  — AI-authored from a citable primary source (BoK PDF,
//                        public legislation). Item-level cite fields point
//                        to specific pages or documents.
//   2. ai-from-notes   — AI-derived from the author's own study notes,
//                        which are themselves a distillation of various
//                        CPACC reference material. One step removed from
//                        primary sources.
//   3. ai-live         — Live AI responses (chat tutor). Not pre-reviewed.
//
// Provenance objects follow this shape:
//   { category, label, citations:[], generatedBy, generatedAt, humanReview,
//     confidence: 'high'|'medium'|'low'|'variable',
//     limitations:[] }
//
// This module renders the badge/disclosure UI. Data files own the metadata.

import { escapeHtml } from './dom.js';

/** Provenance for live chat responses. Static — chat is never pre-reviewed. */
export const CHAT_PROVENANCE = {
  category: 'ai-live',
  label: 'AI live response — not pre-reviewed',
  citations: ['Live response from the configured LLM provider. Per-question chat also receives the question text, choices, BoK rationale, and citation as context.'],
  generatedBy: 'The operator-configured LLM (see LLM_PROVIDER / LLM_MODEL)',
  generatedAt: 'Just now',
  humanReview: 'None — responses are not pre-reviewed.',
  confidence: 'variable',
  limitations: [
    'May produce plausible-sounding but incorrect statements (hallucinations).',
    'Not authorized or endorsed by IAAP.',
    'Verify claims against the BoK or other authoritative sources before relying on them.',
  ],
};

/** Map confidence levels to a paired color + shape glyph + label for SC 1.4.1. */
const CONFIDENCE = {
  high:     { glyph: '●',  text: 'High confidence',     cls: 'pv-conf-high' },
  medium:   { glyph: '◐',  text: 'Medium confidence',   cls: 'pv-conf-med'  },
  low:      { glyph: '○',  text: 'Low confidence',      cls: 'pv-conf-low'  },
  variable: { glyph: '?',  text: 'Variable confidence', cls: 'pv-conf-var' },
};

/**
 * Render the inline badge + collapsible provenance card for one item.
 * Uses native <details>/<summary> for zero-JS disclosure semantics.
 *
 * <summary> maps to role="button", which takes its accessible name from its
 * content — so we let the visible label (prov.label) and confidence text
 * form the name instead of overriding it with aria-label (that would satisfy
 * only sighted users and fail WCAG 2.5.3 Label in Name for speech-input
 * users). itemLabel is appended as a visually-hidden suffix purely to keep
 * each badge's name unique across a page with 20+ of them.
 *
 * @param {object} prov - provenance object (see shape above)
 * @param {string} itemLabel - human label for the item, appended via
 *   .sr-only so screen readers hear "... — AI provenance for Question 4"
 *   after the visible label/confidence, disambiguating repeated badges
 * @returns {string} HTML string
 */
export function renderProvenanceBadge(prov, itemLabel) {
  if (!prov) return '';
  const conf = CONFIDENCE[prov.confidence] || CONFIDENCE.variable;
  const safeLabel = escapeHtml(itemLabel || 'this item');

  return `
    <details class="provenance">
      <summary>
        <span class="pv-icon" aria-hidden="true">🤖</span>
        <span class="pv-cat">${escapeHtml(prov.label)}</span>
        <span class="pv-conf ${conf.cls}">
          <span class="pv-conf-glyph" aria-hidden="true">${conf.glyph}</span> ${conf.text}
        </span>
        <span class="pv-chev" aria-hidden="true">▸</span>
        <span class="sr-only"> — AI provenance for ${safeLabel}</span>
      </summary>
      <dl class="provenance-card">
        ${renderField('Source(s)', (prov.citations || []).join('; '))}
        ${renderField('Generated by', prov.generatedBy)}
        ${renderField('Generated', prov.generatedAt)}
        ${renderField('Human review', prov.humanReview)}
        ${renderField('Confidence', conf.text)}
        ${renderLimitations(prov.limitations || [])}
      </dl>
    </details>
  `;
}

function renderField(term, value) {
  if (!value) return '';
  return `<dt>${escapeHtml(term)}</dt><dd>${escapeHtml(value)}</dd>`;
}

function renderLimitations(items) {
  if (!items.length) return '';
  const lis = items.map(i => `<li>${escapeHtml(i)}</li>`).join('');
  return `<dt>Limitations</dt><dd><ul class="pv-limits">${lis}</ul></dd>`;
}

/**
 * Render the static AI-disclaimer banner shown above each chat transcript.
 * @param {Function} onOpen - called when "About AI in this app" link is clicked
 * @returns {string} HTML string (event wired separately via [data-open-ai-info])
 */
export function renderChatProvenanceBanner() {
  return `
    <div class="pv-banner" role="note">
      <span class="pv-icon" aria-hidden="true">🤖</span>
      <span><b>AI live response — not pre-reviewed.</b> Verify against authoritative sources.</span>
      <button type="button" class="linkish pv-info-link" data-open-ai-info aria-haspopup="dialog">About AI in this app</button>
    </div>
  `;
}

/**
 * Render the page-level "About AI in this app" dialog (closed by default).
 * Returns markup for a native <dialog>. Use installAiInfoDialog() to wire it up.
 */
export function renderAiInfoDialog() {
  return `
    <dialog id="ai-info-dialog" class="ai-dialog" aria-labelledby="ai-info-title">
      <article>
        <header class="row" style="justify-content:space-between;align-items:flex-start">
          <h2 id="ai-info-title" style="margin:0">About AI in this app</h2>
          <button type="button" class="secondary small" data-close-ai-info aria-label="Close dialog">✕</button>
        </header>
        <p>This study app uses AI in three ways. The bundled content was authored ahead of time by Claude; the live chat tutor uses whichever provider the operator configured (Anthropic, OpenAI, or a locally hosted model). Each piece of content is labeled with a provenance badge you can expand for full detail.</p>

        <h3>1. AI-authored from the BoK (high confidence)</h3>
        <p>The main practice question bank was written by Claude directly from the IAAP CPACC Body of Knowledge (October 2023, v4.0). Every item carries a BoK page citation. The author reviewed each item against the cited page.</p>

        <h3>2. AI-derived from author's notes (medium confidence)</h3>
        <p>The Bear-notes practice bank, flashcards, and parts of the disabilities and laws references were generated by Claude from the author's personal study notes. Those notes are themselves the author's distillation of CPACC reference material, so this content is one step removed from primary sources.</p>

        <h3>3. AI live chat (variable confidence, not pre-reviewed)</h3>
        <p>The optional chat tutor sends your message to the configured LLM provider in real time and shows the reply unmodified. Chat replies are <b>not</b> pre-reviewed and may contain hallucinations. The per-question chat receives the question text, choices, BoK rationale, and citation as context to ground the response — but you should still verify against the BoK or other authoritative sources before relying on a chat response.</p>

        <h3>What this is not</h3>
        <ul>
          <li>Not authorized or endorsed by IAAP.</li>
          <li>Not equivalent to the actual CPACC exam (which is 100 questions in 2 hours).</li>
          <li>Not a replacement for the official Body of Knowledge or accredited study materials.</li>
        </ul>

        <h3>How to read confidence pills</h3>
        <dl class="provenance-card">
          <dt><span class="pv-conf pv-conf-high"><span aria-hidden="true">●</span> High</span></dt>
          <dd>Authored from a citable primary source; author reviewed against the citation.</dd>
          <dt><span class="pv-conf pv-conf-med"><span aria-hidden="true">◐</span> Medium</span></dt>
          <dd>Derived from author's notes or secondary sources; spot-checked, not exhaustively reviewed.</dd>
          <dt><span class="pv-conf pv-conf-low"><span aria-hidden="true">○</span> Low</span></dt>
          <dd>Significant uncertainty flagged — usually paired with a visible Confidence note on the item.</dd>
          <dt><span class="pv-conf pv-conf-var"><span aria-hidden="true">?</span> Variable</span></dt>
          <dd>Live AI response; quality varies per query.</dd>
        </dl>

        <p>The full <b>AI_TRANSPARENCY.md</b> document in the project repository covers the three content buckets, per-item provenance shape, confidence pill semantics, and how to file a correction.</p>

        <div class="nav" style="justify-content:flex-end">
          <button type="button" data-close-ai-info>Close</button>
        </div>
      </article>
    </dialog>
  `;
}

/**
 * Wire up the AI-info dialog. Call once after the dialog markup is in the DOM.
 * Returns a cleanup function (idempotent).
 */
export function installAiInfoDialog() {
  const dlg = document.getElementById('ai-info-dialog');
  if (!dlg) return () => {};
  let lastFocus = null;

  function open() {
    lastFocus = document.activeElement;
    if (typeof dlg.showModal === 'function') dlg.showModal();
    else dlg.setAttribute('open', '');
  }
  // The Back/Forward router re-renders <main>, which can detach the
  // original trigger element while the dialog is open. Focusing a detached
  // node is a silent no-op that drops focus to <body>, so fall back to the
  // app root when the trigger is gone.
  function restoreFocus() {
    if (lastFocus && lastFocus.isConnected && typeof lastFocus.focus === 'function') {
      lastFocus.focus();
    } else {
      document.getElementById('app')?.focus();
    }
  }

  // The native 'close' event fires for BOTH dismissal paths: our own
  // dlg.close() call below, and the browser's own Escape handling on a
  // showModal() dialog (which never runs our close() function at all).
  // Handling restoration only here — not also inline in close() — is what
  // guarantees it runs exactly once per dismissal.
  dlg.addEventListener('close', restoreFocus);

  function close() {
    if (typeof dlg.close === 'function') {
      dlg.close(); // dispatches 'close', which runs restoreFocus above
    } else {
      // removeAttribute('open') is the no-native-<dialog> fallback and does
      // NOT dispatch a 'close' event (only HTMLDialogElement.close() and
      // native Escape dismissal do), so this path must restore focus itself.
      dlg.removeAttribute('open');
      restoreFocus();
    }
  }

  document.addEventListener('click', onClick);
  function onClick(e) {
    const opener = e.target.closest('[data-open-ai-info]');
    if (opener) { e.preventDefault(); open(); return; }
    const closer = e.target.closest('[data-close-ai-info]');
    if (closer) { e.preventDefault(); close(); return; }
  }
  // Native <dialog> handles Escape itself in modern browsers; the resulting
  // 'close' event is caught by the listener registered above.

  return () => {
    document.removeEventListener('click', onClick);
    dlg.removeEventListener('close', restoreFocus);
  };
}
